services:
  _defaults:
    autowire: true
    autoconfigure: true
  admin.page:
    class: SonataVue\Admin\PageAdmin
    tags:
      - { name: sonata.admin, model_class: SonataVue\Entity\Page, controller: SonataVue\Controller\PageAdminController, manager_type: orm, group: admin, label: Page }
  admin.page_template:
    class: SonataVue\Admin\PageTemplateAdmin
    tags:
      - { name: sonata.admin, model_class: SonataVue\Entity\PageTemplate, controller: ~, manager_type: orm, group: admin, label: PageTemplate }
  admin.site:
    class: SonataVue\Admin\SiteAdmin
    tags:
      - { name: sonata.admin, model_class: SonataVue\Entity\Site, controller: ~, manager_type: orm, group: admin, label: Site }
  SonataVue\Type\MapType:
    arguments:
      - !tagged_iterator sonata_vue.block_service
  SonataVue\Service\:
      resource: '../../Service/'
  SonataVue\Controller\:
      resource: '../../Controller/'

