services:
  _defaults:
    autowire: true
    autoconfigure: true
  SonataVue\Admin\PageAdmin:
    tags:
      - { name: sonata.admin, model_class: SonataVue\Entity\Page, controller: ~, manager_type: orm, group: admin, label: Page }
  SonataVue\Admin\PageTemplateAdmin:
    tags:
      - { name: sonata.admin, model_class: SonataVue\Entity\PageTemplate, controller: ~, manager_type: orm, group: admin, label: PageTemplate }
  SonataVue\Admin\SiteAdmin:
    tags:
      - { name: sonata.admin, model_class: SonataVue\Entity\Site, controller: ~, manager_type: orm, group: admin, label: Site }
  SonataVue\Type\MapType:
    arguments:
      - !tagged_iterator sonata_vue.block_service
  SonataVue\Service\:
      resource: '../../Service/'
  SonataVue\Controller\:
      resource: '../../Controller/'

